//
//  ExportService.swift
//  ReconKit
//
//  Renders a report to Markdown and saves it via NSSavePanel (sandbox-safe
//  user-selected write).
//

import AppKit
import UniformTypeIdentifiers

enum ExportService {

    // MARK: - Markdown

    static func markdown(for report: ScanReport) -> String {
        var out = "# ReconKit Report — \(report.target)\n\n"
        let iso = ISO8601DateFormatter()
        out += "- **Scanned:** \(iso.string(from: report.date))\n"
        out += "- **Score:** \(report.score)/100 (grade \(report.grade)) — \(report.rating.label)\n"
        let all = report.results.flatMap(\.findings)
        out += "- **Findings:** \(all.filter { $0.severity == .critical }.count) issues, "
        out += "\(all.filter { $0.severity == .warning }.count) warnings, "
        out += "\(all.filter { $0.severity == .pass }.count) passed\n\n"

        let plan = report.actionPlan
        if !plan.isEmpty {
            out += "## Priority Action Plan\n\n"
            for (i, item) in plan.enumerated() {
                out += "\(i + 1). **[\(item.category.rawValue)] \(item.finding.title)** — \(item.fix)\n"
            }
            out += "\n"
        }

        for result in report.results {
            out += "## \(result.category.rawValue)\n\n"
            out += "_\(result.summary)_\n\n"
            for f in result.findings {
                out += "- **[\(f.severity.label)] \(f.title)** — \(f.detail.replacingOccurrences(of: "\n", with: " "))\n"
            }
            out += "\n"
        }
        out += "---\n_Generated by ReconKit for macOS._\n"
        return out
    }

    // MARK: - JSON (structured, for agents/automation)

    static func jsonString(for report: ScanReport) -> String {
        let iso = ISO8601DateFormatter()
        let all = report.results.flatMap(\.findings)

        let summary: [String: Int] = [
            "issues": all.filter { $0.severity == .critical }.count,
            "warnings": all.filter { $0.severity == .warning }.count,
            "passed": all.filter { $0.severity == .pass }.count,
        ]

        var actionPlan: [[String: Any]] = []
        for (idx, item) in report.actionPlan.enumerated() {
            actionPlan.append([
                "priority": idx + 1,
                "category": item.category.rawValue,
                "title": item.finding.title,
                "severity": item.finding.severity.label,
                "detail": item.finding.detail,
                "fix": item.fix,
            ])
        }

        var categories: [[String: Any]] = []
        for result in report.results {
            var findings: [[String: Any]] = []
            for f in result.findings {
                var d: [String: Any] = [
                    "title": f.title,
                    "detail": f.detail,
                    "severity": f.severity.label,
                ]
                if let r = f.remediation { d["remediation"] = r }
                findings.append(d)
            }
            categories.append([
                "category": result.category.rawValue,
                "summary": result.summary,
                "findings": findings,
            ])
        }

        var dict: [String: Any] = [:]
        dict["target"] = report.target
        dict["scannedAt"] = iso.string(from: report.date)
        dict["score"] = report.score
        dict["grade"] = report.grade
        dict["rating"] = report.rating.label
        dict["summary"] = summary
        dict["actionPlan"] = actionPlan
        dict["categories"] = categories

        guard let data = try? JSONSerialization.data(withJSONObject: dict,
                                                     options: [.prettyPrinted, .sortedKeys]),
              let str = String(data: data, encoding: .utf8) else { return "{}" }
        return str
    }

    // MARK: - Save flows

    /// Saves markdown only.
    @discardableResult
    @MainActor
    static func save(report: ScanReport) -> URL? {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.init(filenameExtension: "md") ?? .plainText]
        panel.nameFieldStringValue = "reconkit-\(report.target).md"
        panel.canCreateDirectories = true
        guard panel.runModal() == .OK, let url = panel.url else { return nil }
        try? markdown(for: report).data(using: .utf8)?.write(to: url)
        return url
    }

    /// Saves BOTH a markdown and a JSON file (same base name) from one dialog —
    /// for handing results to AI agents / automation.
    @MainActor
    static func saveForAgents(report: ScanReport) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        panel.nameFieldStringValue = "reconkit-\(report.target)"
        panel.canCreateDirectories = true
        panel.message = "Saves both a .md and a .json report with this name."
        guard panel.runModal() == .OK, let url = panel.url else { return }
        let base = url.deletingPathExtension()
        try? markdown(for: report).data(using: .utf8)?
            .write(to: base.appendingPathExtension("md"))
        try? jsonString(for: report).data(using: .utf8)?
            .write(to: base.appendingPathExtension("json"))
    }

    @MainActor
    static func copyToPasteboard(report: ScanReport) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(markdown(for: report), forType: .string)
    }
}
